monitor=HDMI-A-2,1600x900@60,auto-right,auto
monitor=HEADLESS-2,1600x900@60,0x0,1
monitor=,preferred,auto,auto

workspace = 1, HDMI-A-2, default:true
workspace = 2, HDMI-A-2
workspace = 3, HDMI-A-2
workspace = 4, HDMI-A-2
workspace = 5, HDMI-A-2
workspace = 6, HDMI-A-2
workspace = 7, HDMI-A-2
workspace = 8, HEADLESS-2
workspace = 9, HEADLESS-2
workspace = 0, HEADLESS-2
